### ISSUE TITLE
选中标题的bug

### ISSUE THREAD

**Issue by ShenZhenChenlin** [robinccer/RBPageMenu#1]
选中娱乐标题的时候，下划线没有和标题选中同步，而是移动到标题八卦的下方。同时在出现这个错误的情况下，颜色渐变也会出现混乱。我是初学swift，这两个bug没有修改出来，如果我指出的情况不周，希望作者见谅。

**Comment by robinccer** [comment]
确实有这个问题, 这周抽空处理一下, 感谢关注~~~

**Comment by robinccer** [comment]
已经修改了这个问题
